modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="unusualend"
version="2.2.1"
displayName="Unusual End"
displayURL="https://www.curseforge.com/members/sweetygamer/projects"
logoFile="logo.png"
credits="Sweetygamer / The Unusual Squad"
authors="Sweetygamer, SashKYotoz"
description="Enhance your End experience !"

[[mixins]]
config="mixins.unusualend.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies."unusualend"]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
